version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm run test
      - npm run build
  build:
    commands:
      - echo "Build completed on `date`"
  post_build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p deployment/scripts
      - cp -r dist/* deployment/
      - cp package.json deployment/
      - cp package-lock.json deployment/
      - cp appspec.yml deployment/
      - cp scripts/* deployment/scripts/
      - cd deployment && zip -r ../my-nest-app-${CODEBUILD_BUILD_NUMBER}.zip .

artifacts:
  files:
    - my-nest-app-${CODEBUILD_BUILD_NUMBER}.zip
  discard-paths: yes